//! `kdc compose` — renders a docker-compose.yml for ANY topology the user
//! asks for: `--dpos N --pbft M` (plus bootstrap on testnet; mainnet has
//! its own protocol bootstrap, so only validators are rendered).
//!
//! No fixed node names: services are `bootstrap`, `dpos-1..N`, `pbft-1..M`
//! with collision-free ports. Validator wallets are generated (keystore)
//! unless addresses are provided.

use anyhow::Result;

/// Canonical ports for the FIRST node of each role; subsequent nodes shift
/// by +10/+10 to stay clear of every other role range.
pub fn ports(role: &str, index: usize) -> (u16, u16) {
    match (role, index) {
        ("bootstrap", _) => (8084, 30403),
        ("dpos", 0) => (8082, 30404),
        ("pbft", 0) => (8081, 30505),
        ("dpos", i) => (8082 + (i as u16) * 10, 30404 + (i as u16) * 10),
        (_, i) => (8090 + (i as u16) * 10, 30510 + (i as u16) * 10),
    }
}

pub struct ComposeSpec {
    pub network: String,
    pub dpos_ids: Vec<String>,
    pub pbft_ids: Vec<String>,
    pub bootstrap_nodes: Option<String>,
    pub context: String,
    pub beacon_interval: String,
    pub bidir_sync: String,
}

fn svc_validator(
    out: &mut String,
    role: &str,
    i: usize,
    addr: &str,
    spec: &ComposeSpec,
    boot_enode: &str,
) {
    let name = format!("{role}-{}", i + 1);
    let (http, p2p) = ports(role, i);
    let consensus = role.to_uppercase();
    let dockerfile = if role == "dpos" { "Dockerfile.dpos" } else { "Dockerfile.pbft" };
    out.push_str(&format!(
        r#"  {name}:
    build:
      context: {context}
      dockerfile: {dockerfile}
    container_name: kodechain-{name}
    ports:
      - "{http}:{http}"
      - "{p2p}:{p2p}"
      - "{p2p}:{p2p}/udp"
    environment:
      NETWORK: {network}
      NODE_ID: {addr}
      VALIDATOR_ADDRESS: {addr}
      CONSENSUS_TYPE: {consensus}
      API_PORT: {http}
      P2P_PORT: {p2p}
      DATA_DIR: /app/data
      BOOTSTRAP_NODES: "{boot_enode}"
      BEACON_BLOCK_INTERVAL: {beacon}
    volumes:
      - {name}_data:/app/data
      - ./archives:/app/archives:ro
    depends_on:
      bootstrap:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:{http}/api/node/health"]
      interval: 15s
      timeout: 5s
      retries: 5
    restart: unless-stopped

"#,
        name = name,
        context = spec.context,
        dockerfile = dockerfile,
        http = http,
        p2p = p2p,
        network = spec.network,
        addr = addr,
        consensus = consensus,
        boot_enode = boot_enode,
        beacon = spec.beacon_interval,
    ));
}

/// Render the full compose file. Pure function — unit-tested.
pub fn render(spec: &ComposeSpec, bootstrap_id: Option<&str>) -> Result<String> {
    if spec.network == "mainnet" && spec.bootstrap_nodes.is_none() {
        anyhow::bail!("mainnet needs --bootstrap-nodes (the protocol bootstrap enode)");
    }
    let mut out = String::from(
        "# Generated by `kdc compose` — edit freely or regenerate.\n# Secrets via environment (.env, gitignored), never baked in.\n\nservices:\n",
    );
    // bootstrap first so depends_on targets exist on testnet
    let boot_enode: String;
    if spec.network != "mainnet" {
        let id = bootstrap_id.ok_or_else(|| anyhow::anyhow!("testnet needs the faucet wallet (genesis)"))?;
        let (http, p2p) = ports("bootstrap", 0);
        boot_enode = format!("enode://{id}@bootstrap:{p2p}?http_port={http}");
        out.push_str(&format!(
            r#"  bootstrap:
    build:
      context: {context}
      dockerfile: Dockerfile.bootstrap
    container_name: kodechain-bootstrap
    ports:
      - "{http}:{http}"
      - "{p2p}:{p2p}"
      - "{p2p}:{p2p}/udp"
    environment:
      NETWORK: {network}
      NODE_ID: {id}
      FAUCET_PRIVATE_KEY: ${{FAUCET_PRIVATE_KEY:?define FAUCET_PRIVATE_KEY}}
      API_PORT: {http}
      P2P_PORT: {p2p}
      DATA_DIR: /app/data
      BEACON_BLOCK_INTERVAL: {beacon}
      KODECHAIN_BIDIR_SYNC: {bidir}
    volumes:
      - bootstrap_data:/app/data
      - ./archives:/app/archives:ro
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:{http}/api/node/health"]
      interval: 15s
      timeout: 5s
      retries: 5
    restart: unless-stopped

"#,
            context = spec.context,
            http = http,
            p2p = p2p,
            network = spec.network,
            id = id,
            beacon = spec.beacon_interval,
            bidir = spec.bidir_sync,
        ));
    } else {
        boot_enode = spec.bootstrap_nodes.clone().unwrap();
    }

    for (i, addr) in spec.dpos_ids.iter().enumerate() {
        svc_validator(&mut out, "dpos", i, addr, spec, &boot_enode);
    }
    for (i, addr) in spec.pbft_ids.iter().enumerate() {
        svc_validator(&mut out, "pbft", i, addr, spec, &boot_enode);
    }

    out.push_str("volumes:\n");
    if spec.network != "mainnet" {
        out.push_str("  bootstrap_data:\n");
    }
    for i in 0..spec.dpos_ids.len() {
        out.push_str(&format!("  dpos-{}_data:\n", i + 1));
    }
    for i in 0..spec.pbft_ids.len() {
        out.push_str(&format!("  pbft-{}_data:\n", i + 1));
    }
    // mainnet validators have no local bootstrap to wait for
    if spec.network == "mainnet" {
        out = out.replace(
            "    depends_on:\n      bootstrap:\n        condition: service_healthy\n",
            "",
        );
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn spec(dpos: usize, pbft: usize, network: &str) -> ComposeSpec {
        ComposeSpec {
            network: network.into(),
            dpos_ids: (0..dpos).map(|i| format!("0xdpos{i}")).collect(),
            pbft_ids: (0..pbft).map(|i| format!("0xpbft{i}")).collect(),
            bootstrap_nodes: if network == "mainnet" {
                Some("enode://0xboot@1.2.3.4:30403?http_port=8084".into())
            } else {
                None
            },
            context: ".".into(),
            beacon_interval: "5".into(),
            bidir_sync: "30s".into(),
        }
    }

    #[test]
    fn canonical_ports_for_first_nodes() {
        assert_eq!(ports("bootstrap", 0), (8084, 30403));
        assert_eq!(ports("dpos", 0), (8082, 30404));
        assert_eq!(ports("pbft", 0), (8081, 30505));
    }

    #[test]
    fn shifted_ports_never_collide() {
        let mut seen = std::collections::HashSet::new();
        for i in 0..10 {
            for role in ["dpos", "pbft"] {
                let (h, p) = ports(role, i);
                assert!(seen.insert(h as u32), "http collision {role}-{i}");
                assert!(seen.insert(p as u32 + 40000), "p2p collision {role}-{i}");
            }
        }
        assert!(seen.insert(8084));
        assert!(seen.insert(30403 + 40000));
    }

    #[test]
    fn renders_n_validators_no_fixed_names() {
        let yml = render(&spec(2, 1, "testnet"), Some("0xboot")).unwrap();
        for svc in ["bootstrap:", "dpos-1:", "dpos-2:", "pbft-1:"] {
            assert!(yml.contains(svc), "missing {svc}");
        }
        assert!(!yml.contains("dpos01") && !yml.contains("pbft01"), "no fixed names");
        // bootstrap enode uses service DNS + canonical ports
        assert!(yml.contains("enode://0xboot@bootstrap:30403?http_port=8084"));
        // fail-fast secrets
        assert!(yml.contains("FAUCET_PRIVATE_KEY:?"));
    }

    #[test]
    fn mainnet_has_no_bootstrap_service() {
        let yml = render(&spec(1, 1, "mainnet"), None).unwrap();
        assert!(!yml.contains("bootstrap:"));
        assert!(!yml.contains("depends_on:"));
        assert!(yml.contains("enode://0xboot@1.2.3.4:30403?http_port=8084"));
        assert!(render(
            &ComposeSpec { bootstrap_nodes: None, ..spec(1, 0, "mainnet") },
            None
        )
        .is_err());
    }
}
